apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  #argocd.argoproj.io/hook: PostSync
  name: hpa
  namespace: opencart
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: opencart-application
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
