apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  argocd.argoproj.io/sync-wave: "-2"
  #argocd.argoproj.io/hook: PreSync
  name: sealed-secrets-controller
  namespace: default
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    # How to get correct target revision number???
    targetRevision: 2.2.0
    helm:
      releaseName: sealed-secrets-controller
  destination:
    server: "https://kubernetes.default.svc"
    namespace: opencart 
  
  syncPolicy:
  # uncomment to create namespace if not present
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true