apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  #argocd.argoproj.io/sync-wave: "-2"
  name: argo-cd
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: 
  project: default
  source:
    path: apps/templates/
    repoURL: https://github.com/oscarWoj/opencartTestRepo.git
    targetRevision: HEAD
  syncPolicy:

    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: default
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argo-cd
data:
  resource.customizations: |
    argoproj.io/Application:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs
